### PR TITLE
added tnrn9b.c, header/make_file modified, etc.

### PR DESCRIPTION
**Pull request by tnrn9b**
This should be right now.

### CODE REVIEW

**Comment by scottgs** [comment]
Message from the repository:
We can’t automatically merge this pull request. 

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b tnrn9b-master master
git pull https://github.com/tnrn9b/swe-spring-2015.git master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff tnrn9b-master
git push origin master

**Comment by tnrn9b** [comment]
I think this should be ready. Thanks for the help!

**Comment by scottgs** [comment]
Please comment back your issues / resolution if you have time for the benefit of others.

**Comment by tnrn9b** [comment]
The best suggestion I have is to make sure to have a good diff editor (http://meldmerge.org/) to help with resolving merge conflicts. Also, configure git to ignore files using the patterns: .o, .a, .~. That way you can just git commit -a -m <comment>. It save lots of time.

**Comment by scottgs** [comment]
Hmmm....This is the default .gitignore on the project.  It doesn't have the tilde, but has the others.

scottgs@srs3 ~/swe-spring-2015 $ cat .gitignore 
# Object files
*.o
*.ko
*.obj
*.elf

# Precompiled Headers
*.gch
*.pch

# Libraries
*.lib
*.a
*.la
*.lo

# Shared objects (inc. Windows DLLs)
*.dll
*.so
*.so.*
*.dylib

# Executables
*.exe
*.out
*.app
*.i*86
*.x86_64
*.hex

**Pull request merged**
