### PR TITLE
apcvzb - hw1 submission

### PR DESCRIPTION
**Pull request by interputed**
unable to push directly, had to fork my own

Andrew Craighead (apcvzb@mail.missouri.edu)

### CODE REVIEW

**Comment by redrip** [comment]
can you post what is the error message so i can help you

**Comment by interputed** [comment]
It worked when I created a fork and submitted a pull request. Did you reject my pull request? That was my submission...

**Comment by mhenke10** [comment]
I'm able to pull and commit/merge but when I attempt to push I get the
error

The requested URL returned error: 403 Forbidden while accessing
https://github.com/scottgs/swe-spring-2015.git/info/refs

**Comment by redrip** [comment]
interputed : no i didn't reject anything or even touch anything

mhenke10: you should be a collaborator to pull, you either can do a pull request or let the professor add you as a collaborator

**Comment by scottgs** [comment]
This does not allow a merge:

## We can’t automatically merge this pull request.

to resolve conflicts before continuing.
## Checkout via command line

If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.
HTTPS Git Patch

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b interputed-apcvzb master
git pull git://github.com/interputed/swe-spring-2015.git apcvzb

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff interputed-apcvzb
git push origin master

**Pull request closed without merging**
